#' Simulation of ecological data structured by single ecological gradient
#' @author David Zeleny (zeleny.david@@gmail.com) - based on the scripts of Jason Fridley (Fridley et al. 2007, Appendix S2) and David Zeleny (Zeleny 2009, Appendix S1)


#' @param S Total number of species in simulation.
#' @param grad Number of ecological gradients (default is \code{grad = 1}).
#' @param gr.length Length of the gradient in arbitrary units. 
#' @param niche.type Shape of species response curves ('random', 'normal', 'skewed').
#' @param max.niche.breath Maximum niche breath along the gradient (default = \code{gr.length})
#' @param min.niche.breath Minimum niche breath along the gradient (default = \code{10}). Cannot be more than \code{max.niche.breath}.
#' @param amplitude Amplitude of species response curve (height in its optimum). Default is to generate amplitude as random values from lognormal distribution (with meanlog = 2 and sdlog = 1). Can be vector of numeric values; if the vector is shorter than \code{totS}, the values are recycled. If all amplitudes should be equal, supply vector of the length one.
#' @param tau When calculating niche of the species, consider species occurrences only if their probabilities are above this threshold. Could be also zero.
#' @param spec.optima Distribution of species optima along simulated gradient. Either one of \code{'random'}, \code{'unimodal'} or \code{'skewed'}, or a vector (of the length equal to \code{totS}) with numbers (ranging between 1 and \code{gr.length}). Default = \code{'random'}.
#' @param prop.random.species Proportion of random species, i.e. species which are not related to the gradient. Should be real number from [0,1]. These species are generated by randomizing occurrence of given proportion of species among samples. Default = 0.
#' @param seed Set random seed for reproducing always the same result.
#' @param sico Object created by \code{simul.comm} function with parameters of individual species response curves.
#' @param Np Number of samples to be generated.
#' @param sampling Positions of sampling locations along the gradient. Default = \code{"random"}, meaning that random locations are generated. Other options include \code{"equal"} with samples distributed in equal distances, \code{"biased"} with samples accumulated toward higher values of the gradient. Can be also vector of the same length as \code{Np} with exact positions of the samples.
#' @param no.ind Mean number of individuals to be sampled from the species pool (if \code{based.on = 'individuals'}).
#' @param cv.no.ind Coefficient of variation of number of indiduals sampled from the species pool. Increasing it allows to create set of samples with various levels of undersampling.
#' @param k Mean proportion of species from species pool to be drawn into local community (if \code{based.on = 'species'}). If only one number is given, in each sample given proportion of species will be sampled from species pool. If vector of two numbers (range of \code{k} valus) is given, random \code{k} in given range will be generated (with uniform distribution) for each sample; this allows to vary the degree of undersampling among generated samples.
#' @param pa Result table will be generated in presence-absence form (default \code{pa = FALSE}).
#' @param based.on Should the sampling of species from species pool be based on \code{'individuals'} or \code{'species'}? (default = \code{'individuals'})
#' @param standardize.rowsums Standardizes the abundances of species in samples so as the sum of species abundances in sample is 100 (standardizes to rowsums equal to 100). Applies only if \code{pa = FALSE}. Default = \code{TRUE}.
#' @return The function \code{simul.comm} returns \code{list} with the following items, describing the set of parameters used to simulate community of species response curves:
#' \itemize{
#' \item \code{S} Total number of species in simulation.
#' \item \code{grad} Number of ecological gradients.
#' \item \code{gr.length} Length of the gradient(s).
#' \item \code{niche.type} Shape of species response curves.
#' \item \code{Ao} Vector of species amplitudes for the simulated gradient (heights of species response curves, corresponding to maximum probability of species to be selected to community in species optima).
#' \item \code{m} Vector of species optima along the simulated gradient.
#' \item \code{r} Vector of generated species ranges along the simulated gradient (generated niche breaths).
#' \item \code{width} Vector of realised species ranges along the simulated gradient, considering the truncation of species response curves by gradient margins (these differ from \code{r} especially at the gradient margins, where the generated species niche may be wide, but since the margin cuts the species occurrences, realised species niche is narrower.)
#' \item \code{niche} The volume of realized species niche (sum of species occurrences above the \code{tau} value).
#' \item \code{a, g} Vectors of shape parameters for curves (used in beta function to generate the shape of the species response curve)
#' \item \code{A.all} List of matrices (one matrix for each gradient), with each matrix representing simulated probabilities of occurrences for each species along each point of the gradient.
#' }
#' The function \code{sample.comm} returns \code{list} of the following items with parameters of generated community data; the last item contains also all items returned by \code{simul.comm} function:
#' \itemize{
#' \item \code{a.mat} The list with matrices for each gradient; one matrix (sample x species) contains species abundances in samples for each gradient.
#' \item \code{p.mat} The list with matrices for each gradient; one matrix (sample x species) contains species occurrence probabilities in samples for each gradient.
#' \item \code{sample.x} The list of vectors for each gradient; each vector contains positions of samples along the simulated gradient.
#' \item \code{args.samcom} List of the items storing initial settings of arguments in \code{sample.comm} (namely arguments \code{Np, sampling, based.on, no.ind, k, seed, pa, standardize.rowsums}).
#' \item \code{args.simcom} List of the items returned by function \code{simul.comm} (namely arguments \code{S, grad, gr.length, niche.type, Ao, m, r, width, niche, a, g, A.all}).
#' }

#' @rdname simul.comm
#' @export
simul.comm <- function (S = 30, grad = 1, gr.length = 500, niche.type = 'random', max.niche.breath = gr.length, min.niche.breath = gr.length/100, amplitude = NULL, tau = 0.05, spec.optima = 'random', prop.random.species = 0, seed = NULL)
{
  if (!is.null (seed)) set.seed (seed)
  
  #This is beta function for generating niches
  curve <- function (Ao,m,r,a,g,x)
    (Ao*((((x-m)/r)+(a/(a+g)))^a)*((1-(((x-m)/r)+(a/(a+g))))^g))/(((a/(a+g))^a)*((1-(a/(a+g)))^g))
  curve1d <- function (m,r,a,g,x)
    (((((x-m)/r)+(a/(a+g)))^a)*((1-(((x-m)/r)+(a/(a+g))))^g))/(((a/(a+g))^a)*((1-(a/(a+g)))^g))
  
  width <- vector ('list', length = grad)
  
  if (grad > 1 & length (gr.length) == 1) gr.length <- rep (gr.length, grad)
  if (grad > 1 & length (gr.length) > 1) gr.length <- rep (gr.length, length = grad)
  if (grad > 1 & length (max.niche.breath) == 1) max.niche.breath <- rep (max.niche.breath, grad)
  if (grad > 1 & length (min.niche.breath) == 1) min.niche.breath <- rep (min.niche.breath, grad)
  
  x <- lapply (1:grad, FUN = function (gr) seq(1, gr.length[gr], by = 1)) # sequence of values for each gradient (as a list)
  names (x) <- paste ('gr', 1:length (x), sep = '')
  
  if (is.null (amplitude)) Ao <- rlnorm(S, 2, 1) else Ao <- rep (amplitude, length.out = S) #amplitude vector (lognormal distribution or assigned)
  
  if (spec.optima == 'random')  m <- lapply (1:grad, FUN = function (gr) sample (seq (5, gr.length[gr]-5), S, replace = T)) else
    if (spec.optima == 'unimodal') {
      #starting <- lapply (1:grad, FUN = function (gr) seq (1, gr.length[gr], by = gr.length[gr]/10))
      biased <- c(20,40,60,80,100,100,80,60,40,20)  # keep the same structure as in Zeleny 2009, Appendix S1
      m <- lapply (1:grad, FUN = function (gr) 
        sample (seq (5, gr.length[gr]-5), S, prob = biased [cut (seq (5, gr.length[gr]-5), breaks = 10, labels = FALSE)]/sum (biased [cut (seq (5, gr.length[gr]-5), breaks = 10, labels = FALSE)]), replace = T))
    } else
      if (spec.optima == 'skewed'){
        #starting <- seq (1, gr.length, by = gr.length/10)
        biased <- c(20, 40, 60, 80, 100, 120, 140, 160, 180, 200) # keep the same structure as in Zeleny 2009, Appendix S1
        m <- lapply (1:grad, FUN = function (gr) 
          sample (seq (5, gr.length[gr]-5), S, prob = biased [cut (seq (5, gr.length[gr]-5), breaks = 10, labels = FALSE)]/sum (biased [cut (seq (5, gr.length[gr]-5), breaks = 10, labels = FALSE)]), replace = T))
      } else if (length (spec.optima) == S) m <- spec.optima else stop ("Argument spec.optima needs to be correctly defined.")
  
  r <- lapply (1:grad, FUN = function (gr) { 
    y <- runif (S, min=min.niche.breath[gr], max=max.niche.breath[gr])
    names (y) <- paste ('spec_', 1:S, sep = '')
    y  #range along gradient (niche breadth)
  })
  
  # species values for random niches
  if(niche.type=="random") {
    a <- lapply (1:grad, FUN = function (gr) runif (S, min=.1, max=4))		#shape parameter (alpha)
    g <- lapply (1:grad, FUN = function (gr) runif (S, min=.1, max=4))		#shape parameter (gamma)
  }
  
  # species values for normal niches
  if(niche.type=="normal") {
    a <- lapply (1:grad, FUN = function (gr) rep (1.99, S))				#shape parameter (alpha)
    g <- lapply (1:grad, FUN = function (gr) rep (1.99, S))				#shape parameter (gamma)
  }
  
  # species values for skewed niches - #produces skews in either direction, randomly
  if(niche.type=="skewed") {
    sample.gr <- lapply (1:grad, FUN = function (gr) sample (c(1,2), S, replace = TRUE))
    a <- lapply (1:grad, FUN = function (gr) c(1.99, .25)[sample.gr[[gr]]])
    g <- lapply (1:grad, FUN = function (gr) c(.25, 1.99)[sample.gr[[gr]]])
  }
  
  A.all <- vector ("list", length = grad)
  for (gr in 1:grad){
    temp <- matrix(0, nrow = gr.length[gr], ncol = S)
    for (L in 1:S)
      temp[,L] <- curve1d(m[[gr]][L], r[[gr]][L], a[[gr]][L], g[[gr]][L], x[[gr]])
    temp[is.na (temp)] <- 0
    A.all[[gr]] <- temp
  }
  
  if (prop.random.species[1] > 0){
    rand.spec <- sample (1:S, round (prop.random.species[1]*S))
    for (gr in 1:grad)
      A.all[[gr]][,rand.spec] <- apply (A.all[[gr]][,rand.spec], 2, sample)
  }
  
  for (gr in 1:grad) {
    width[[gr]] <- colSums (A.all[[gr]] > 0)
    names (width[[gr]]) <- paste ('spec_', 1:S, sep = '')  
  }
  
  lens <- vapply(A.all, FUN = function (m) nrow (m), integer(1))
  arr_1 <- array (1, dim = lens)
  volume <- sum (arr_1)
  niche <- vector ('numeric', length = S)
  for (L in 1:S){
    arr <- arr_1
    for (i in seq_len (grad)) {
      arr <- sweep (arr, i, A.all[[i]][,L], `*`)
    }
    niche[L] <- sum(arr >= tau)/volume
  }
  
  result <- list (S = S, grad = grad, gr.length = gr.length, niche.type = niche.type, Ao = Ao, m = m, r = r, width = width, niche = niche, a = a, g = g, A.all = A.all)
  class (result) <- 'simcom'
  return (result)
}

#' @rdname simul.comm
#' @export
sample.comm <- function (sico = NULL, Np = 100, sampling = "random", no.ind = 100, cv.no.ind = 0.01, k = 0.2, seed = NULL, pa = FALSE, based.on = 'individuals', standardize.rowsums = TRUE)
{
  if (!is.null (seed)) set.seed (seed)
  if (is.null (sico)) sico <- simul.comm ()
  BASED.ON <- c('individuals', 'species')
  based.on <- match.arg (based.on, BASED.ON)
  
  list2env(sico, envir = environment ())
  
  #Random sample intervals along gradient
  sample.x <- vector ('list', length = grad)
  if (sampling == "random") for (gr in seq (1, grad)) sample.x[[gr]] <- trunc(sample(c(2:gr.length[gr])-1, Np, replace = T)) else
    #Equal sample intervals along gradient
    if (sampling == "equal") for (gr in seq (1, grad)) sample.x[[gr]] <- trunc(seq(2, gr.length[gr]-1, length=Np)) else
      #Biased sample intervals along gradient
      if (sampling == 'biased')
        for (gr in seq (1, grad)) {
          exp.x <- sort (rexp(Np, rate=20))
          exp.sample.x <- trunc(exp.x/(max(exp.x))*(gr.length[gr]-1))
          while(length(unique(exp.sample.x)) != Np)
            exp.sample.x[duplicated(exp.sample.x)] <- exp.sample.x[duplicated(exp.sample.x)]+1
          sample.x[[gr]] <- rev(gr.length[gr]-exp.sample.x)	#switch to other side of gradient
        }
  
  sample.list <- lapply(1:grad, function (gr) A.all[[gr]][sample.x[[gr]],,drop = FALSE])    # the plot-numbers are in sample.x defined above
  p.mat <- sweep (Reduce(`*`, sample.list), 2, Ao, `*`)
  
  a.mat <- p.mat*0 # prepared abundance matrix
  
  #output data frames
  samp.out.rand <- matrix(0, nrow = Np, ncol = S)
  
  #Sampling for random-sample-interval based on individuals
  if (based.on == 'individuals')
  {
    draws.rand <- round(rnorm(Np, mean = no.ind, sd = cv.no.ind * no.ind))
    draws.rand [draws.rand <= 0] <- 1  # if the number of individuals should be zero or negative, replace by one (to avoid empty samples)
    for(i in 1:Np) {
      samp.prob <- p.mat[i,]		#probabilities of sampling each species in given location (based on rel abundance)
      if (sum (samp.prob) > 0) 
      {
        tab.samp <- table(sample(c(1:S), size = draws.rand[i], prob = samp.prob, replace = TRUE)) 	#tabulated vector of sp identities after choosing "draws" no. of individuals
        a.mat[i,][as.numeric(names(tab.samp))] <- tab.samp
      } else a.mat[i,] <- 0
    } 
  }
  #Sampling for random-sample-interval based on no of species
  if (based.on == 'species')
    for (i in 1:Np) {
      samp.prob <- p.mat [i,]
      spec.pool.size <- sum (samp.prob > 0)
      #no.spec <- round (rnorm (1, k * spec.pool.size))
      if (length (k) == 1) no.spec <- round (k*spec.pool.size) else
        if (length (k) == 2) no.spec <- round (runif (1, min = k[1], max = k[2]) * spec.pool.size)
      if (no.spec <= 0) no.spec <- 1
      if (no.spec > sum (samp.prob > 0)) no.spec <- sum (samp.prob > 0) # if number of selected species should be higher than number of nonzero probabilities, it must decrease
      if (sum (samp.prob) > 0) 
      {
        tab.samp <- table(sample(c(1:S), size = no.spec, prob = samp.prob, replace = FALSE))  #tabulated vector of spp identities after choosing no of species
        a.mat[i,][as.numeric(names(tab.samp))] <- tab.samp*samp.prob[as.numeric(names(tab.samp))]
      } else a.mat[i,] <- 0
    }
  
  colnames (p.mat) <- paste ('spec_', 1:dim (p.mat)[2], sep = '')
  colnames (a.mat) <- paste ('spec_', 1:dim (a.mat)[2], sep = '')
  if (standardize.rowsums) a.mat <- vegan::decostand (a.mat, method = 'total')*100
  if (pa) a.mat[a.mat>0] <- 1		#presence-absence version
  
  result <- list (a.mat = a.mat, p.mat = p.mat, sample.x = sample.x, args.samcom = list (Np = Np, sampling = sampling, based.on = based.on, no.ind = no.ind, k = k, seed = seed, pa = pa, standardize.rowsums = standardize.rowsums), args.simcom = sico)
  class (result) <- 'samcom'
  return (result)
}

#' @rdname simul.comm
#' @param sico Object returned by the function \code{simul.comm}.
#' @param xlab Label of the x-axis. Default to "Gradient".
#' @param ylab Label of the y-axis. Default to "Abundance".
#' @param minmax Highlight two species response curve by colour: the one with minimum and maximum niche width.
#' @param spec.highlight List of species numbers to be highlighted by colour (integers).
#' @param mfrow Setting of \code{mfrow} parameter in \code{par}, influencing how the panels with response curves along individual gradients will be plotted.
#' @param ... Other parameters passed into \code{plot_simcom}.
#' @export
plot_simcom <- function (sico, xlab = "Gradient", ylab = "Abundance", minmax = FALSE, spec.highlight = NULL, mfrow = NULL, ...)  
{
  list2env(sico, envir = environment ())
  x <- vector ('list', length = grad)
  for (gr in seq (1, grad)) x[[gr]] <- seq (1, gr.length[gr]) 
  if (!is.null (mfrow)) par (mfrow = mfrow) else par (mfrow = c(grad, 1))
  for (gr in 1:grad){
    plot (x[[gr]], A.all[[gr]][,1]*Ao[1], xlim = c(0,max(x[[gr]])), ylim = c(0,max(Ao)), type="l", xlab = paste ("Gradient", gr, sep = ' '), ylab="Abundance", cex.lab=1.7, cex.axis=1.5, lwd=2)
    for(L in 2:S) {
      lines (x[[gr]], A.all[[gr]][,L]*Ao[L])
    }
    if (minmax){
      max.range <- which (range[[gr]] == max (range[[gr]]))
      min.range <- which (range[[gr]] == min (range[[gr]]))
      lines(x[[gr]], A.all[[gr]][, max.range[1]]*Ao[max.range[1]],lwd=3,col=2)
      lines(x[[gr]], A.all[[gr]][, min.range[1]]*Ao[min.range[1]],lwd=3,col=3)
    }
    if (!is.null (spec.highlight))
      for (co in spec.highlight)
        lines(x[[gr]], A.all[[gr]][,co]*Ao[co], lwd=3, col='red')
  }
}